// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAztCy1X59RWsTu6R-HsMk3d9jIu5OdX6A',
    appId: '1:1097175702254:android:02985fd844b9960878f1ff',
    messagingSenderId: '1097175702254',
    projectId: 'targetly',
    storageBucket: 'targetly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAPVEguRC_KNsn71Vk5vefLFow0K9MSDI',
    appId: '1:1097175702254:ios:3948c23b34cd495178f1ff',
    messagingSenderId: '1097175702254',
    projectId: 'targetly',
    storageBucket: 'targetly.appspot.com',
    iosClientId: '1097175702254-qhn4hbv07k2o5941kit0ov5vrvet8gk3.apps.googleusercontent.com',
    iosBundleId: 'app.targetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAPVEguRC_KNsn71Vk5vefLFow0K9MSDI',
    appId: '1:1097175702254:ios:3948c23b34cd495178f1ff',
    messagingSenderId: '1097175702254',
    projectId: 'targetly',
    storageBucket: 'targetly.appspot.com',
    iosClientId: '1097175702254-qhn4hbv07k2o5941kit0ov5vrvet8gk3.apps.googleusercontent.com',
    iosBundleId: 'app.targetly',
  );
}
